### ISSUE TITLE
How to use this module ???

### ISSUE THREAD

**Issue by maravilhosinga** [natanrolnik/parse-server-generator#1]
Any explanation will be good, for biginners

**Comment by natanrolnik** [comment]
Olá @maravilhosinga :)

1 - First, you need to install node/npm. If you already have it installed, go to the 2; to install it, you can either download from www.nodejs.org or if you have homebrew, `brew install node`.
2 - In the command line, run `npm install -g parse-server-generator` to install it globally in your environment.
3 - Run `parse-server-generator` and then answer to the questions (provide your applicationId, masterKey, mongo URI, etc.). In case you are moving from Parse.com, you can take from there; otherwise, you need to generate the random strings.
4 - After the process is finished, you can see the files generated. In case you want to change some of the values (like Mongo URI, you can open the `.npmrc` file). Run `npm start` to start the server in `localhost:1337/parse`.

You can also take a [look at this bash script in the Parse-Server repo](https://github.com/ParsePlatform/parse-server/blob/master/bootstrap.sh) - it is similar and will give you more or less the same results. To do so, run `curl https://raw.githubusercontent.com/ParsePlatform/parse-server/master/bootstrap.sh | sh`

**Comment by maravilhosinga** [comment]
Thanks all done!

Can you please look at this [repo](https://github.com/maravilhosinga/parse-server-accountkit-auth)  and give me an idea of how to use this in Android or iOS 
Please ???

**Comment by natanrolnik** [comment]
@maravilhosinga glad it helped you.
I'm not familiar but I may try in the next days.
